# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envi < Formula
  desc "CLI tool to push and pull .env files to/from GitHub Gists"
  homepage "https://github.com/dexterity-inc/envi"
  version "1.0.10"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/dexterity-inc/envi/releases/download/v1.0.10/envi-darwin-amd64.tar.gz"
      sha256 "6994607788f8d530221520d18669653bacaffedf0e159da6d43215e27c09b479"

      def install
        system "go", "build", *std_go_args
      end
    end
    on_arm do
      url "https://github.com/dexterity-inc/envi/releases/download/v1.0.10/envi-darwin-arm64.tar.gz"
      sha256 "c46a807cb94c3ca634f6da5df11d40926fc290af6b4a19d2e698b7c7679b72ca"

      def install
        system "go", "build", *std_go_args
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dexterity-inc/envi/releases/download/v1.0.10/envi-linux-amd64.tar.gz"
        sha256 "c36ffd2439235a642be9205bfe064ef61154ee1a15e0110787fffea251656a3e"

        def install
          system "go", "build", *std_go_args
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dexterity-inc/envi/releases/download/v1.0.10/envi-linux-arm64.tar.gz"
        sha256 "4b54aef32348d90eee9aeffbf1603f321472309f5f54e42ab603b233af35aefb"

        def install
          system "go", "build", *std_go_args
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        envi config --token <your_github_token>
    EOS
  end

  test do
    assert_match "environment variable management", shell_output("#{bin}/envi --help")
  end
end
