# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envi < Formula
  desc "CLI tool to push and pull .env files to/from GitHub Gists"
  homepage "https://github.com/dexterity-inc/envi"
  version "1.0.13"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/dexterity-inc/envi/releases/download/v1.0.13/envi-darwin-amd64.tar.gz"
      sha256 "b45629efd5bb4c6213a1cf6377c38b0995b8f0e07b1ce12694465d3cab92dce4"

      def install
        system "go", "build", *std_go_args
      end
    end
    on_arm do
      url "https://github.com/dexterity-inc/envi/releases/download/v1.0.13/envi-darwin-arm64.tar.gz"
      sha256 "1cbea650c477c81698b7393d5d31c697c927be1d8e74d48c65ea96ec3f5e0997"

      def install
        system "go", "build", *std_go_args
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dexterity-inc/envi/releases/download/v1.0.13/envi-linux-amd64.tar.gz"
        sha256 "a7c67afc10d06ae79e113edfa6d35a2269ae4366d740a24ea673b7fe40773a07"

        def install
          system "go", "build", *std_go_args
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dexterity-inc/envi/releases/download/v1.0.13/envi-linux-arm64.tar.gz"
        sha256 "c5722348b16aeb2d8cf053cf0fe22ad33b79d7f2caa1c161ab05c3765d597467"

        def install
          system "go", "build", *std_go_args
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        envi config --token <your_github_token>
    EOS
  end

  test do
    assert_match "environment variable management", shell_output("#{bin}/envi --help")
  end
end
