# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envi < Formula
  desc "CLI tool to push and pull .env files to/from GitHub Gists"
  homepage "https://github.com/dexterity-inc/envi"
  version "1.0.14"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/dexterity-inc/envi/releases/download/v1.0.14/envi-darwin-amd64.tar.gz"
      sha256 "afa8320fde461e46b92441b4e72419cd531f6ad30f1da8ed529231d52f9914c1"

      def install
        system "go", "build", *std_go_args
      end
    end
    on_arm do
      url "https://github.com/dexterity-inc/envi/releases/download/v1.0.14/envi-darwin-arm64.tar.gz"
      sha256 "c3f7bd1ba0df09089508549a9def0c14b52764e8a242fe4ac67a4722de6b66c1"

      def install
        system "go", "build", *std_go_args
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dexterity-inc/envi/releases/download/v1.0.14/envi-linux-amd64.tar.gz"
        sha256 "afb1408e9347e1aae4378e000562daba83ace5790fae48c185736e61243abf0e"

        def install
          system "go", "build", *std_go_args
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dexterity-inc/envi/releases/download/v1.0.14/envi-linux-arm64.tar.gz"
        sha256 "bac5d518e2740b8fba16991031e65a38a0efe401ca8c11bf0b47b7c079d2a209"

        def install
          system "go", "build", *std_go_args
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        envi config --token <your_github_token>
    EOS
  end

  test do
    assert_match "environment variable management", shell_output("#{bin}/envi --help")
  end
end
