# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Envi < Formula
  desc "CLI tool to push and pull .env files to/from GitHub Gists"
  homepage "https://github.com/dexterity-inc/envi"
  version "1.0.17"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    on_intel do
      url "https://github.com/dexterity-inc/envi/releases/download/v1.0.17/envi-darwin-amd64.tar.gz"
      sha256 "18f6789ffa2ce0c85f0bd86f3be04892020b00a82991b9e29cfa213922f75bb2"

      def install
        bin.install "envi"
      end
    end
    on_arm do
      url "https://github.com/dexterity-inc/envi/releases/download/v1.0.17/envi-darwin-arm64.tar.gz"
      sha256 "06caa3cb8a824db622b5cfa42f80328fbc59e27c7fc733621fde5d5661d1e3b8"

      def install
        bin.install "envi"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dexterity-inc/envi/releases/download/v1.0.17/envi-linux-amd64.tar.gz"
        sha256 "194df3aef9f0f0f019bda6037caf8c8d88b39e1a298292d38458d46d80eb34d2"

        def install
          bin.install "envi"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dexterity-inc/envi/releases/download/v1.0.17/envi-linux-arm64.tar.gz"
        sha256 "8c2ebd05f8dca8f98715a1c1e25c852a4e948773cc275bbe17c867364c77d41f"

        def install
          bin.install "envi"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        envi config --token <your_github_token>
    EOS
  end

  test do
    assert_match "environment variable management", shell_output("#{bin}/envi --help")
  end
end
